import { env } from "cloudflare:workers";

type TrackInput = { spotifyId: string; uri: string; name: string; artist: string; album: string; imageUrl: string | null; durationMs: number };
function database() { if (!env.DB) throw new Error("De verzoeklijst is tijdelijk niet beschikbaar."); return env.DB; }
export async function getSetting(key: string) { const row = await database().prepare("SELECT value FROM settings WHERE key = ?").bind(key).first<{ value: string }>(); return row?.value ?? null; }
export async function setSettings(values: Record<string, string>) { const db = database(); const now = Date.now(); await db.batch(Object.entries(values).map(([key, value]) => db.prepare("INSERT INTO settings (key, value, updated_at) VALUES (?, ?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at").bind(key, value, now))); }
export async function listTracks(voterId: string) { const result = await database().prepare(`SELECT s.id, s.spotify_id AS spotifyId, s.uri, s.name, s.artist, s.album, s.image_url AS imageUrl, s.duration_ms AS durationMs, s.status, COUNT(v.id) AS votes, MAX(CASE WHEN v.voter_id = ? THEN 1 ELSE 0 END) AS hasVoted FROM suggestions s LEFT JOIN votes v ON v.suggestion_id = s.id GROUP BY s.id ORDER BY CASE WHEN s.status = 'candidate' THEN 0 ELSE 1 END, votes DESC, s.created_at ASC`).bind(voterId).all(); return result.results.map((row) => ({ ...row, votes: Number(row.votes), hasVoted: Boolean(row.hasVoted) })); }
export async function addSuggestion(track: TrackInput, voterId: string) { const db = database(); const now = Date.now(); await db.prepare("INSERT INTO suggestions (spotify_id, uri, name, artist, album, image_url, duration_ms, status, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, 'candidate', ?) ON CONFLICT(spotify_id, status) DO NOTHING").bind(track.spotifyId, track.uri, track.name, track.artist, track.album, track.imageUrl, track.durationMs, now).run(); const item = await db.prepare("SELECT id FROM suggestions WHERE spotify_id = ? AND status = 'candidate'").bind(track.spotifyId).first<{ id: number }>(); if (!item) throw new Error("Nummer kon niet worden toegevoegd."); await db.prepare("INSERT INTO votes (suggestion_id, voter_id, created_at) VALUES (?, ?, ?) ON CONFLICT(suggestion_id, voter_id) DO NOTHING").bind(item.id, voterId, now).run(); return item.id; }
export async function addVote(itemId: number, voterId: string) { const db = database(); const exists = await db.prepare("SELECT id FROM suggestions WHERE id = ? AND status = 'candidate'").bind(itemId).first(); if (!exists) throw new Error("Dit nummer staat niet meer open voor stemmen."); await db.prepare("INSERT INTO votes (suggestion_id, voter_id, created_at) VALUES (?, ?, ?) ON CONFLICT(suggestion_id, voter_id) DO NOTHING").bind(itemId, voterId, Date.now()).run(); }
export async function getTrack(itemId: number) { return database().prepare("SELECT id, uri, name, status FROM suggestions WHERE id = ?").bind(itemId).first<{ id: number; uri: string; name: string; status: string }>(); }
export async function markQueued(itemId: number) { await database().prepare("UPDATE suggestions SET status = 'queued' WHERE id = ?").bind(itemId).run(); }
